const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const P=JSON.parse(localStorage.getItem("deutschProgress")||"{}");let lesson,words=[],mode="flash",q=[],pos=0,right=0,wrongs=[],answered=false,retryPool=[];
const save=()=>localStorage.setItem("deutschProgress",JSON.stringify(P)),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const level=id=>+id.slice(1)<=6?"A1.1":"A1.2",art=w=>["der","die","das"].includes(String(w.Gender).toLowerCase())?String(w.Gender).toLowerCase():"",de=w=>art(w)?`${art(w)} ${w.Word_German}`:w.Word_German;
function mark(w,ok){P[w.Vocab_ID]??={right:0,wrong:0};P[w.Vocab_ID][ok?"right":"wrong"]++;save();stats()}
function stats(){$("#total").textContent=VOCABULARY.length;$("#learned").textContent=Object.values(P).filter(x=>x.right>0).length;$("#review").textContent=Object.values(P).filter(x=>x.wrong>x.right).length}
function lessons(){let f=$("#filter").value;$("#grid").innerHTML="";LESSONS.filter(l=>f==="all"||level(l.Lesson_ID)===f).forEach(l=>{let ws=VOCABULARY.filter(v=>v.Lesson_ID===l.Lesson_ID),d=ws.filter(v=>P[v.Vocab_ID]?.right>0).length,e=document.createElement("div");e.className="lesson";e.innerHTML=`<div class="num">${level(l.Lesson_ID)} · ${l.Lektion_No}</div><h3>${l.Title_German}</h3><p>${l.Title_Thai||""}</p><div class="lm"><span>${ws.length} คำ</span><span>เคยตอบถูก ${d}</span></div>`;e.onclick=()=>openLesson(l);$("#grid").append(e)})}
function openLesson(l){lesson=l;words=VOCABULARY.filter(v=>v.Lesson_ID===l.Lesson_ID);$("#home").classList.add("hidden");$("#practice").classList.remove("hidden");$("#level").textContent=`${level(l.Lesson_ID)} · ${l.Lektion_No}`;$("#ptitle").textContent=l.Title_German;$("#pthai").textContent=l.Title_Thai||"";setup()}
function home(){$("#practice").classList.add("hidden");$("#home").classList.remove("hidden");lessons();stats()}
function hide(){["setup","flashPanel","quizPanel","articlePanel","result"].forEach(x=>$(`#${x}`).classList.add("hidden"))}
function setup(){hide();$("#setup").classList.remove("hidden");$$(".tabs button").forEach(b=>b.classList.remove("active"))}
function start(m,pool=null){mode=m;let base=pool||words;if(m==="article")base=base.filter(art);if(!base.length){alert("บทนี้ไม่มีคำที่ใช้กับโหมดนี้");return setup()}q=shuffle(base).slice(0,m==="flash"?base.length:Math.min(10,base.length));pos=right=0;wrongs=[];answered=false;hide();$(`#${m}Panel`).classList.remove("hidden");$$(".tabs button").forEach(b=>b.classList.toggle("active",b.dataset.mode===m));render()}
function render(){answered=false;if(pos>=q.length)return finish();let w=q[pos],n=q.length,p=Math.round(pos/n*100);
if(mode==="flash"){$("#flashCount").textContent=`คำที่ ${pos+1} / ${n}`;$("#flashScore").textContent=`จำได้ ${right}`;$("#flashBar").style.width=p+"%";$("#de").textContent=de(w);$("#th").textContent=w.Word_Thai;$("#cat").textContent=w.Category||"";$("#extra").textContent=w.Plural&&w.Plural!=="-"?`Plural: ${w.Plural}`:"";$("#answer").classList.add("hidden");$("#hint").classList.remove("hidden")}
if(mode==="quiz"){$("#quizCount").textContent=`ข้อ ${pos+1} / ${n}`;$("#quizScore").textContent=`ถูก ${right}`;$("#quizBar").style.width=p+"%";$("#question").textContent=w.Word_Thai;$("#feedback").textContent="";$("#nextQuiz").classList.add("hidden");let opts=shuffle([...shuffle(VOCABULARY.filter(x=>x.Vocab_ID!==w.Vocab_ID)).slice(0,3),w]);$("#options").innerHTML="";opts.forEach(x=>{let b=document.createElement("button");b.textContent=de(x);b.onclick=()=>quiz(b,x,w);$("#options").append(b)})}
if(mode==="article"){$("#articleCount").textContent=`ข้อ ${pos+1} / ${n}`;$("#articleScore").textContent=`ถูก ${right}`;$("#articleBar").style.width=p+"%";$("#aword").textContent=w.Word_German;$("#athai").textContent=w.Word_Thai;$("#afeedback").textContent="";$("#nextArticle").classList.add("hidden");$$("#articles button").forEach(b=>{b.disabled=false;b.className=""})}}
function record(w,ok){if(answered)return;answered=true;mark(w,ok);if(ok)right++;else wrongs.push(w)}
function flash(ok){let w=q[pos];record(w,ok);pos++;render()}
function quiz(btn,x,w){if(answered)return;let ok=x.Vocab_ID===w.Vocab_ID;record(w,ok);$$("#options button").forEach(b=>{b.disabled=true;if(b.textContent===de(w))b.classList.add("correct")});if(!ok)btn.classList.add("wrong");$("#feedback").textContent=ok?"✓ ถูกต้อง":`คำตอบ: ${de(w)}`;$("#quizScore").textContent=`ถูก ${right}`;$("#nextQuiz").classList.remove("hidden")}
function article(btn){if(answered)return;let w=q[pos],ok=btn.textContent===art(w);record(w,ok);$$("#articles button").forEach(b=>{b.disabled=true;if(b.textContent===art(w))b.classList.add("correct")});if(!ok)btn.classList.add("wrong");$("#afeedback").textContent=ok?"✓ ถูกต้อง":`คำตอบ: ${art(w)} ${w.Word_German}`;$("#articleScore").textContent=`ถูก ${right}`;$("#nextArticle").classList.remove("hidden")}
function finish(){hide();$("#result").classList.remove("hidden");let n=q.length,p=Math.round(right/n*100);$("#rscore").textContent=`${right} / ${n}`;$("#rpct").textContent=`${p}%`;$("#rsummary").textContent=wrongs.length?`มี ${wrongs.length} คำที่ควรทบทวนต่อ`:"รอบนี้ตอบถูกทั้งหมด";$("#wrongList").innerHTML="";wrongs.forEach(w=>{let d=document.createElement("div");d.className="wrongitem";d.innerHTML=`<b>${de(w)}</b><span>${w.Word_Thai}</span>`;$("#wrongList").append(d)});retryPool=[...wrongs];$("#retry").classList.toggle("hidden",!wrongs.length)}
$("#filter").onchange=lessons;$("#back").onclick=home;$("#homeBtn").onclick=home;$("#card").onclick=()=>{$("#answer").classList.remove("hidden");$("#hint").classList.add("hidden")};$("#again").onclick=()=>flash(false);$("#know").onclick=()=>flash(true);$("#nextQuiz").onclick=()=>{pos++;render()};$("#nextArticle").onclick=()=>{pos++;render()};$$("#articles button").forEach(b=>b.onclick=()=>article(b));$$("[data-start]").forEach(b=>b.onclick=()=>start(b.dataset.start));$$(".tabs button").forEach(b=>b.onclick=()=>start(b.dataset.mode));$("#retry").onclick=()=>start(mode,retryPool);$("#againSession").onclick=()=>start(mode);$("#resultBack").onclick=home;stats();lessons();